// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Mono.Profiler {
    
    
    public partial class HeapSnapshotExplorer {
        
        private Gtk.HPaned hpaned1;
        
        private Gtk.ScrolledWindow GtkScrolledWindow;
        
        private Gtk.TreeView Tree;
        
        private Gtk.ScrolledWindow GtkScrolledWindow1;
        
        private Gtk.NodeView PerClassStatistics;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Mono.Profiler.HeapSnapshotExplorer
            Stetic.BinContainer.Attach(this);
            this.Name = "Mono.Profiler.HeapSnapshotExplorer";
            // Container child Mono.Profiler.HeapSnapshotExplorer.Gtk.Container+ContainerChild
            this.hpaned1 = new Gtk.HPaned();
            this.hpaned1.CanFocus = true;
            this.hpaned1.Name = "hpaned1";
            this.hpaned1.Position = 124;
            // Container child hpaned1.Gtk.Paned+PanedChild
            this.GtkScrolledWindow = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            this.Tree = new Gtk.TreeView();
            this.Tree.CanFocus = true;
            this.Tree.Name = "Tree";
            this.GtkScrolledWindow.Add(this.Tree);
            this.hpaned1.Add(this.GtkScrolledWindow);
            Gtk.Paned.PanedChild w2 = ((Gtk.Paned.PanedChild)(this.hpaned1[this.GtkScrolledWindow]));
            w2.Resize = false;
            // Container child hpaned1.Gtk.Paned+PanedChild
            this.GtkScrolledWindow1 = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
            this.GtkScrolledWindow1.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
            this.PerClassStatistics = new Gtk.NodeView();
            this.PerClassStatistics.CanFocus = true;
            this.PerClassStatistics.Name = "PerClassStatistics";
            this.GtkScrolledWindow1.Add(this.PerClassStatistics);
            this.hpaned1.Add(this.GtkScrolledWindow1);
            this.Add(this.hpaned1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.Tree.ButtonPressEvent += new Gtk.ButtonPressEventHandler(this.OnTreeButtonPress);
            this.PerClassStatistics.ButtonPressEvent += new Gtk.ButtonPressEventHandler(this.OnListButtonPress);
        }
    }
}
