// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Mono.Profiler {
    
    
    public partial class MainWindow {
        
        private Mono.Profiler.HeapSnapshotExplorer heapExplorer;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Mono.Profiler.MainWindow
            this.Name = "Mono.Profiler.MainWindow";
            this.Title = Mono.Unix.Catalog.GetString("MainWindow");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Container child Mono.Profiler.MainWindow.Gtk.Container+ContainerChild
            this.heapExplorer = new Mono.Profiler.HeapSnapshotExplorer();
            this.heapExplorer.Events = ((Gdk.EventMask)(256));
            this.heapExplorer.Name = "heapExplorer";
            this.Add(this.heapExplorer);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 468;
            this.DefaultHeight = 300;
            this.Show();
            this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        }
    }
}
