// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Mono.CSharp.Gui {
    
    
    public partial class MainWindow {
        
        private Gtk.UIManager UIManager;
        
        private Gtk.Action FileAction;
        
        private Gtk.Action QuitAction;
        
        private Gtk.Action AttachToProcessAction;
        
        private Gtk.Action HelpAction;
        
        private Gtk.Action AboutAction;
        
        private Gtk.Action ViewAction;
        
        private Gtk.ToggleAction gtkpane;
        
        private Gtk.VBox vbox1;
        
        private Gtk.MenuBar menubar1;
        
        private Gtk.Notebook notebook1;
        
        private Gtk.HPaned hpaned;
        
        private Gtk.EventBox paned_container;
        
        private Gtk.EventBox eventbox;
        
        private Gtk.Label label1;
        
        private Gtk.EventBox standalone_container;
        
        private Gtk.ScrolledWindow sw;
        
        private Gtk.Label label2;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Mono.CSharp.Gui.MainWindow
            this.UIManager = new Gtk.UIManager();
            Gtk.ActionGroup w1 = new Gtk.ActionGroup("Default");
            this.FileAction = new Gtk.Action("FileAction", Mono.Unix.Catalog.GetString("_File"), null, null);
            this.FileAction.ShortLabel = Mono.Unix.Catalog.GetString("File");
            w1.Add(this.FileAction, null);
            this.QuitAction = new Gtk.Action("QuitAction", Mono.Unix.Catalog.GetString("_Quit"), null, "gtk-quit");
            this.QuitAction.ShortLabel = Mono.Unix.Catalog.GetString("_Quit");
            w1.Add(this.QuitAction, null);
            this.AttachToProcessAction = new Gtk.Action("AttachToProcessAction", Mono.Unix.Catalog.GetString("Attach to Process"), null, null);
            this.AttachToProcessAction.ShortLabel = Mono.Unix.Catalog.GetString("Attach to Process");
            w1.Add(this.AttachToProcessAction, null);
            this.HelpAction = new Gtk.Action("HelpAction", Mono.Unix.Catalog.GetString("Help"), null, null);
            this.HelpAction.ShortLabel = Mono.Unix.Catalog.GetString("Help");
            w1.Add(this.HelpAction, null);
            this.AboutAction = new Gtk.Action("AboutAction", Mono.Unix.Catalog.GetString("About"), null, null);
            this.AboutAction.ShortLabel = Mono.Unix.Catalog.GetString("About");
            w1.Add(this.AboutAction, null);
            this.ViewAction = new Gtk.Action("ViewAction", Mono.Unix.Catalog.GetString("View"), null, null);
            this.ViewAction.ShortLabel = Mono.Unix.Catalog.GetString("View");
            w1.Add(this.ViewAction, null);
            this.gtkpane = new Gtk.ToggleAction("gtkpane", Mono.Unix.Catalog.GetString("Gtk Pane"), null, null);
            this.gtkpane.ShortLabel = Mono.Unix.Catalog.GetString("Gtk Pane");
            w1.Add(this.gtkpane, null);
            this.UIManager.InsertActionGroup(w1, 0);
            this.AddAccelGroup(this.UIManager.AccelGroup);
            this.Name = "Mono.CSharp.Gui.MainWindow";
            this.Title = Mono.Unix.Catalog.GetString("MainWindow");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.DefaultWidth = 600;
            this.DefaultHeight = 500;
            // Container child Mono.CSharp.Gui.MainWindow.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.UIManager.AddUiFromString("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='AttachToProcessAction' action='AttachToProcessAction'/><separator/><menuitem name='QuitAction' action='QuitAction'/></menu><menu name='ViewAction' action='ViewAction'><menuitem name='gtkpane' action='gtkpane'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='AboutAction' action='AboutAction'/></menu></menubar></ui>");
            this.menubar1 = ((Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
            this.menubar1.Name = "menubar1";
            this.vbox1.Add(this.menubar1);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.notebook1 = new Gtk.Notebook();
            this.notebook1.CanFocus = true;
            this.notebook1.Name = "notebook1";
            this.notebook1.CurrentPage = 1;
            this.notebook1.ShowBorder = false;
            this.notebook1.ShowTabs = false;
            // Container child notebook1.Gtk.Notebook+NotebookChild
            this.hpaned = new Gtk.HPaned();
            this.hpaned.CanFocus = true;
            this.hpaned.Name = "hpaned";
            this.hpaned.Position = 472;
            // Container child hpaned.Gtk.Paned+PanedChild
            this.paned_container = new Gtk.EventBox();
            this.paned_container.Name = "paned_container";
            this.hpaned.Add(this.paned_container);
            Gtk.Paned.PanedChild w3 = ((Gtk.Paned.PanedChild)(this.hpaned[this.paned_container]));
            w3.Resize = false;
            // Container child hpaned.Gtk.Paned+PanedChild
            this.eventbox = new Gtk.EventBox();
            this.eventbox.Name = "eventbox";
            this.hpaned.Add(this.eventbox);
            this.notebook1.Add(this.hpaned);
            // Notebook tab
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("page1");
            this.notebook1.SetTabLabel(this.hpaned, this.label1);
            this.label1.ShowAll();
            // Container child notebook1.Gtk.Notebook+NotebookChild
            this.standalone_container = new Gtk.EventBox();
            this.standalone_container.Name = "standalone_container";
            // Container child standalone_container.Gtk.Container+ContainerChild
            this.sw = new Gtk.ScrolledWindow();
            this.sw.CanFocus = true;
            this.sw.Name = "sw";
            this.sw.ShadowType = ((Gtk.ShadowType)(1));
            this.standalone_container.Add(this.sw);
            this.notebook1.Add(this.standalone_container);
            Gtk.Notebook.NotebookChild w7 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.standalone_container]));
            w7.Position = 1;
            // Notebook tab
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("page2");
            this.notebook1.SetTabLabel(this.standalone_container, this.label2);
            this.label2.ShowAll();
            this.vbox1.Add(this.notebook1);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.vbox1[this.notebook1]));
            w8.Position = 1;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
            this.QuitAction.Activated += new System.EventHandler(this.OnQuitActionActivated);
            this.AttachToProcessAction.Activated += new System.EventHandler(this.OnAttachToProcessActionActivated);
        }
    }
}
