//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.Rules.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.Rules.Globalization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap ImageInBothCultures {
            get {
                object obj = ResourceManager.GetObject("ImageInBothCultures", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageOnlyInEnglish {
            get {
                object obj = ResourceManager.GetObject("ImageOnlyInEnglish", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello!.
        /// </summary>
        internal static string StringInBothLanguages {
            get {
                return ResourceManager.GetString("StringInBothLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A string.
        /// </summary>
        internal static string StringInEnglishImageInFrench {
            get {
                return ResourceManager.GetString("StringInEnglishImageInFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s all !.
        /// </summary>
        internal static string StringOnlyInEnglish {
            get {
                return ResourceManager.GetString("StringOnlyInEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First: {0} Second: {1} Third: {2}.
        /// </summary>
        internal static string StringWith3ParametersEnBut12Fr {
            get {
                return ResourceManager.GetString("StringWith3ParametersEnBut12Fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last parameter: {64}.
        /// </summary>
        internal static string StringWithMoreThan64Parameters {
            get {
                return ResourceManager.GetString("StringWithMoreThan64Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First: {0} Second: {1} Third: {2}.
        /// </summary>
        internal static string StringWithThreeParameters {
            get {
                return ResourceManager.GetString("StringWithThreeParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First: {0} Third: {2}.
        /// </summary>
        internal static string StringWithThreeParametersButSomeUnused {
            get {
                return ResourceManager.GetString("StringWithThreeParametersButSomeUnused", resourceCulture);
            }
        }
    }
}
