// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.Action File;
    
    private Gtk.Action quit;
    
    private Gtk.Action Compare;
    
    private Gtk.Action Custom;
    
    private Gtk.Action a;
    
    private Gtk.Action b;
    
    private Gtk.VBox vbox1;
    
    private Gtk.MenuBar menubar1;
    
    private Gtk.ScrolledWindow GtkScrolledWindow;
    
    private Gtk.TreeView tree;
    
    private Gtk.Statusbar statusbar1;
    
    private Gtk.ProgressBar progressbar1;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        Gtk.UIManager w1 = new Gtk.UIManager();
        Gtk.ActionGroup w2 = new Gtk.ActionGroup("Default");
        this.File = new Gtk.Action("File", Mono.Unix.Catalog.GetString("_File"), null, null);
        this.File.ShortLabel = Mono.Unix.Catalog.GetString("File");
        w2.Add(this.File, null);
        this.quit = new Gtk.Action("quit", Mono.Unix.Catalog.GetString("_Quit"), null, "gtk-quit");
        this.quit.ShortLabel = Mono.Unix.Catalog.GetString("_Quit");
        w2.Add(this.quit, null);
        this.Compare = new Gtk.Action("Compare", Mono.Unix.Catalog.GetString("_Compare"), null, null);
        this.Compare.ShortLabel = Mono.Unix.Catalog.GetString("Compare");
        w2.Add(this.Compare, null);
        this.Custom = new Gtk.Action("Custom", Mono.Unix.Catalog.GetString("Custom..."), null, null);
        this.Custom.ShortLabel = Mono.Unix.Catalog.GetString("Custom...");
        w2.Add(this.Custom, null);
        this.a = new Gtk.Action("a", Mono.Unix.Catalog.GetString("a"), null, null);
        this.a.ShortLabel = Mono.Unix.Catalog.GetString("a");
        w2.Add(this.a, null);
        this.b = new Gtk.Action("b", Mono.Unix.Catalog.GetString("b"), null, null);
        this.b.ShortLabel = Mono.Unix.Catalog.GetString("b");
        w2.Add(this.b, null);
        w1.InsertActionGroup(w2, 0);
        this.AddAccelGroup(w1.AccelGroup);
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("MainWindow");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.Name = "vbox1";
        this.vbox1.Spacing = 6;
        // Container child vbox1.Gtk.Box+BoxChild
        w1.AddUiFromString("<ui><menubar name='menubar1'><menu action='File'><menuitem action='quit'/></menu><menu action='Compare'><menuitem action='Custom'/><separator/></menu></menubar></ui>");
        this.menubar1 = ((Gtk.MenuBar)(w1.GetWidget("/menubar1")));
        this.menubar1.Name = "menubar1";
        this.vbox1.Add(this.menubar1);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
        w3.Position = 0;
        w3.Expand = false;
        w3.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.GtkScrolledWindow = new Gtk.ScrolledWindow();
        this.GtkScrolledWindow.Name = "GtkScrolledWindow";
        this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
        // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
        this.tree = new Gtk.TreeView();
        this.tree.CanFocus = true;
        this.tree.Name = "tree";
        this.tree.HeadersClickable = true;
        this.GtkScrolledWindow.Add(this.tree);
        this.vbox1.Add(this.GtkScrolledWindow);
        Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
        w5.Position = 1;
        // Container child vbox1.Gtk.Box+BoxChild
        this.statusbar1 = new Gtk.Statusbar();
        this.statusbar1.Name = "statusbar1";
        this.statusbar1.Spacing = 6;
        // Container child statusbar1.Gtk.Box+BoxChild
        this.progressbar1 = new Gtk.ProgressBar();
        this.progressbar1.Name = "progressbar1";
        this.statusbar1.Add(this.progressbar1);
        Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.statusbar1[this.progressbar1]));
        w6.Position = 2;
        this.vbox1.Add(this.statusbar1);
        Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.vbox1[this.statusbar1]));
        w7.Position = 2;
        w7.Expand = false;
        w7.Fill = false;
        this.Add(this.vbox1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 484;
        this.DefaultHeight = 300;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.quit.Activated += new System.EventHandler(this.OnQuitActivated);
    }
}
