// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.UIManager UIManager;
    
    private Gtk.Action File;
    
    private Gtk.Action quit;
    
    private Gtk.Action Compare;
    
    private Gtk.Action Custom;
    
    private Gtk.Action a;
    
    private Gtk.Action b;
    
    private Gtk.Action View;
    
    private Gtk.ToggleAction ShowMissing;
    
    private Gtk.ToggleAction ShowExtra;
    
    private Gtk.ToggleAction ShowPresent;
    
    private Gtk.ToggleAction ShowErrors;
    
    private Gtk.Action Refresh;
    
    private Gtk.ToggleAction ShowTodo;
    
    private Gtk.Action RecentComparisons;
    
    private Gtk.ToggleAction ShowNotImplemented;
    
    private Gtk.Action ToggleRowExpansionAction;
    
    private Gtk.VBox vbox1;
    
    private Gtk.MenuBar menubar1;
    
    private Gtk.Notebook notebook1;
    
    private Gtk.ScrolledWindow GtkScrolledWindow;
    
    private Gtk.TreeView tree;
    
    private Gtk.Label label1;
    
    private Gtk.Label label3;
    
    private Gtk.Label label2;
    
    private Gtk.Label summary;
    
    private Gtk.Expander expander1;
    
    private Gtk.Table table1;
    
    private Gtk.Label label4;
    
    private Gtk.Label label5;
    
    private Gtk.Label label6;
    
    private Gtk.Label label7;
    
    private Gtk.Label label8;
    
    private Gtk.Label label9;
    
    private Gtk.Image legendImageError;
    
    private Gtk.Image legendImageExtra;
    
    private Gtk.Image legendImageMissing;
    
    private Gtk.Image legendImageNIEX;
    
    private Gtk.Image legendImageOK;
    
    private Gtk.Image legendImageTODO;
    
    private Gtk.VSeparator vseparator1;
    
    private Gtk.VSeparator vseparator2;
    
    private Gtk.VSeparator vseparator3;
    
    private Gtk.Label GtkLabel4;
    
    private Gtk.Statusbar statusbar1;
    
    private Gtk.ProgressBar progressbar1;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.UIManager = new Gtk.UIManager();
        Gtk.ActionGroup w1 = new Gtk.ActionGroup("Default");
        this.File = new Gtk.Action("File", Mono.Unix.Catalog.GetString("_File"), null, null);
        this.File.ShortLabel = Mono.Unix.Catalog.GetString("File");
        w1.Add(this.File, null);
        this.quit = new Gtk.Action("quit", Mono.Unix.Catalog.GetString("_Quit"), null, "gtk-quit");
        this.quit.ShortLabel = Mono.Unix.Catalog.GetString("_Quit");
        w1.Add(this.quit, null);
        this.Compare = new Gtk.Action("Compare", Mono.Unix.Catalog.GetString("_Compare"), null, null);
        this.Compare.ShortLabel = Mono.Unix.Catalog.GetString("Compare");
        w1.Add(this.Compare, null);
        this.Custom = new Gtk.Action("Custom", Mono.Unix.Catalog.GetString("Custom..."), null, null);
        this.Custom.ShortLabel = Mono.Unix.Catalog.GetString("Custom...");
        w1.Add(this.Custom, null);
        this.a = new Gtk.Action("a", Mono.Unix.Catalog.GetString("a"), null, null);
        this.a.ShortLabel = Mono.Unix.Catalog.GetString("a");
        w1.Add(this.a, null);
        this.b = new Gtk.Action("b", Mono.Unix.Catalog.GetString("b"), null, null);
        this.b.ShortLabel = Mono.Unix.Catalog.GetString("b");
        w1.Add(this.b, null);
        this.View = new Gtk.Action("View", Mono.Unix.Catalog.GetString("_View"), null, null);
        this.View.ShortLabel = Mono.Unix.Catalog.GetString("View");
        w1.Add(this.View, null);
        this.ShowMissing = new Gtk.ToggleAction("ShowMissing", Mono.Unix.Catalog.GetString("Show missing"), null, null);
        this.ShowMissing.Active = true;
        this.ShowMissing.ShortLabel = Mono.Unix.Catalog.GetString("Show missing");
        w1.Add(this.ShowMissing, null);
        this.ShowExtra = new Gtk.ToggleAction("ShowExtra", Mono.Unix.Catalog.GetString("Show extra"), null, null);
        this.ShowExtra.Active = true;
        this.ShowExtra.ShortLabel = Mono.Unix.Catalog.GetString("Show extra");
        w1.Add(this.ShowExtra, null);
        this.ShowPresent = new Gtk.ToggleAction("ShowPresent", Mono.Unix.Catalog.GetString("Show present"), null, null);
        this.ShowPresent.Active = true;
        this.ShowPresent.ShortLabel = Mono.Unix.Catalog.GetString("Show present");
        w1.Add(this.ShowPresent, null);
        this.ShowErrors = new Gtk.ToggleAction("ShowErrors", Mono.Unix.Catalog.GetString("Show errors"), null, null);
        this.ShowErrors.Active = true;
        this.ShowErrors.ShortLabel = Mono.Unix.Catalog.GetString("Show errors");
        w1.Add(this.ShowErrors, null);
        this.Refresh = new Gtk.Action("Refresh", Mono.Unix.Catalog.GetString("Refresh"), null, "gtk-refresh");
        this.Refresh.ShortLabel = Mono.Unix.Catalog.GetString("Refresh");
        w1.Add(this.Refresh, "<Control>r");
        this.ShowTodo = new Gtk.ToggleAction("ShowTodo", Mono.Unix.Catalog.GetString("Show Todo"), null, null);
        this.ShowTodo.Active = true;
        this.ShowTodo.ShortLabel = Mono.Unix.Catalog.GetString("Show Todo");
        w1.Add(this.ShowTodo, null);
        this.RecentComparisons = new Gtk.Action("RecentComparisons", Mono.Unix.Catalog.GetString("Recent Comparisons"), null, null);
        this.RecentComparisons.ShortLabel = Mono.Unix.Catalog.GetString("Recent Comparisons");
        w1.Add(this.RecentComparisons, null);
        this.ShowNotImplemented = new Gtk.ToggleAction("ShowNotImplemented", Mono.Unix.Catalog.GetString("Show NotImplemented"), null, null);
        this.ShowNotImplemented.Active = true;
        this.ShowNotImplemented.ShortLabel = Mono.Unix.Catalog.GetString("Show NotImplemented");
        w1.Add(this.ShowNotImplemented, null);
        this.ToggleRowExpansionAction = new Gtk.Action("ToggleRowExpansionAction", Mono.Unix.Catalog.GetString("Toggle Row Expansion"), null, null);
        this.ToggleRowExpansionAction.ShortLabel = Mono.Unix.Catalog.GetString("Toggle Row Expansion");
        w1.Add(this.ToggleRowExpansionAction, "<Mod2>space");
        this.UIManager.InsertActionGroup(w1, 0);
        this.AddAccelGroup(this.UIManager.AccelGroup);
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("GUI CorCompare");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.Name = "vbox1";
        this.vbox1.Spacing = 6;
        // Container child vbox1.Gtk.Box+BoxChild
        this.UIManager.AddUiFromString("<ui><menubar name='menubar1'><menu name='File' action='File'><menu name='RecentComparisons' action='RecentComparisons'/><separator/><menuitem name='Refresh' action='Refresh'/><separator/><menuitem name='quit' action='quit'/></menu><menu name='Compare' action='Compare'><menuitem name='Custom' action='Custom'/></menu><menu name='View' action='View'><menuitem name='ShowErrors' action='ShowErrors'/><menuitem name='ShowMissing' action='ShowMissing'/><menuitem name='ShowNotImplemented' action='ShowNotImplemented'/><menuitem name='ShowExtra' action='ShowExtra'/><menuitem name='ShowTodo' action='ShowTodo'/><menuitem name='ShowPresent' action='ShowPresent'/><separator/><menuitem name='ToggleRowExpansionAction' action='ToggleRowExpansionAction'/></menu></menubar></ui>");
        this.menubar1 = ((Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
        this.menubar1.Name = "menubar1";
        this.vbox1.Add(this.menubar1);
        Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
        w2.Position = 0;
        w2.Expand = false;
        w2.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.notebook1 = new Gtk.Notebook();
        this.notebook1.CanFocus = true;
        this.notebook1.Name = "notebook1";
        this.notebook1.CurrentPage = 1;
        this.notebook1.ShowBorder = false;
        this.notebook1.ShowTabs = false;
        // Container child notebook1.Gtk.Notebook+NotebookChild
        this.GtkScrolledWindow = new Gtk.ScrolledWindow();
        this.GtkScrolledWindow.Name = "GtkScrolledWindow";
        this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
        // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
        this.tree = new Gtk.TreeView();
        this.tree.CanFocus = true;
        this.tree.Name = "tree";
        this.GtkScrolledWindow.Add(this.tree);
        this.notebook1.Add(this.GtkScrolledWindow);
        // Notebook tab
        this.label1 = new Gtk.Label();
        this.label1.Name = "label1";
        this.label1.LabelProp = Mono.Unix.Catalog.GetString("page1");
        this.notebook1.SetTabLabel(this.GtkScrolledWindow, this.label1);
        this.label1.ShowAll();
        // Container child notebook1.Gtk.Notebook+NotebookChild
        this.label3 = new Gtk.Label();
        this.label3.Name = "label3";
        this.label3.Xpad = 20;
        this.label3.Ypad = 20;
        this.label3.LabelProp = Mono.Unix.Catalog.GetString("This tool allows you to compare the API of assemblies.\n\nTo initiate a comparison, use the \"Compare\" menu and use one of the presets based on the assemblies you  have installed on your system and some popular profiles, or use \"Custom\" to define your own comparison");
        this.label3.Wrap = true;
        this.notebook1.Add(this.label3);
        Gtk.Notebook.NotebookChild w5 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.label3]));
        w5.Position = 1;
        // Notebook tab
        this.label2 = new Gtk.Label();
        this.label2.Name = "label2";
        this.label2.LabelProp = Mono.Unix.Catalog.GetString("page2");
        this.notebook1.SetTabLabel(this.label3, this.label2);
        this.label2.ShowAll();
        this.vbox1.Add(this.notebook1);
        Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox1[this.notebook1]));
        w6.Position = 1;
        // Container child vbox1.Gtk.Box+BoxChild
        this.summary = new Gtk.Label();
        this.summary.Name = "summary";
        this.summary.Xpad = 6;
        this.summary.Ypad = 6;
        this.summary.Xalign = 0F;
        this.summary.UseMarkup = true;
        this.vbox1.Add(this.summary);
        Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.vbox1[this.summary]));
        w7.Position = 2;
        w7.Expand = false;
        w7.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.expander1 = new Gtk.Expander(null);
        this.expander1.CanFocus = true;
        this.expander1.Name = "expander1";
        // Container child expander1.Gtk.Container+ContainerChild
        this.table1 = new Gtk.Table(((uint)(3)), ((uint)(5)), false);
        this.table1.Name = "table1";
        this.table1.RowSpacing = ((uint)(6));
        this.table1.ColumnSpacing = ((uint)(6));
        // Container child table1.Gtk.Table+TableChild
        this.label4 = new Gtk.Label();
        this.label4.Name = "label4";
        this.label4.Xalign = 1F;
        this.label4.LabelProp = Mono.Unix.Catalog.GetString("Missing");
        this.table1.Add(this.label4);
        Gtk.Table.TableChild w8 = ((Gtk.Table.TableChild)(this.table1[this.label4]));
        w8.TopAttach = ((uint)(1));
        w8.BottomAttach = ((uint)(2));
        w8.LeftAttach = ((uint)(3));
        w8.RightAttach = ((uint)(4));
        w8.XOptions = ((Gtk.AttachOptions)(4));
        w8.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.label5 = new Gtk.Label();
        this.label5.Name = "label5";
        this.label5.Xalign = 1F;
        this.label5.LabelProp = Mono.Unix.Catalog.GetString("TODO");
        this.table1.Add(this.label5);
        Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.table1[this.label5]));
        w9.TopAttach = ((uint)(2));
        w9.BottomAttach = ((uint)(3));
        w9.XOptions = ((Gtk.AttachOptions)(4));
        w9.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.label6 = new Gtk.Label();
        this.label6.Name = "label6";
        this.label6.Xalign = 1F;
        this.label6.LabelProp = Mono.Unix.Catalog.GetString("Extra");
        this.table1.Add(this.label6);
        Gtk.Table.TableChild w10 = ((Gtk.Table.TableChild)(this.table1[this.label6]));
        w10.TopAttach = ((uint)(2));
        w10.BottomAttach = ((uint)(3));
        w10.LeftAttach = ((uint)(3));
        w10.RightAttach = ((uint)(4));
        w10.XOptions = ((Gtk.AttachOptions)(4));
        w10.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.label7 = new Gtk.Label();
        this.label7.Name = "label7";
        this.label7.Xalign = 1F;
        this.label7.LabelProp = Mono.Unix.Catalog.GetString("Not implemented");
        this.table1.Add(this.label7);
        Gtk.Table.TableChild w11 = ((Gtk.Table.TableChild)(this.table1[this.label7]));
        w11.TopAttach = ((uint)(1));
        w11.BottomAttach = ((uint)(2));
        w11.XOptions = ((Gtk.AttachOptions)(4));
        w11.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.label8 = new Gtk.Label();
        this.label8.Name = "label8";
        this.label8.Xalign = 1F;
        this.label8.LabelProp = Mono.Unix.Catalog.GetString("No errors");
        this.label8.Justify = ((Gtk.Justification)(2));
        this.table1.Add(this.label8);
        Gtk.Table.TableChild w12 = ((Gtk.Table.TableChild)(this.table1[this.label8]));
        w12.XOptions = ((Gtk.AttachOptions)(4));
        w12.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.label9 = new Gtk.Label();
        this.label9.Name = "label9";
        this.label9.Xalign = 1F;
        this.label9.LabelProp = Mono.Unix.Catalog.GetString("Error");
        this.table1.Add(this.label9);
        Gtk.Table.TableChild w13 = ((Gtk.Table.TableChild)(this.table1[this.label9]));
        w13.LeftAttach = ((uint)(3));
        w13.RightAttach = ((uint)(4));
        w13.XOptions = ((Gtk.AttachOptions)(4));
        w13.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.legendImageError = new Gtk.Image();
        this.legendImageError.Name = "legendImageError";
        this.table1.Add(this.legendImageError);
        Gtk.Table.TableChild w14 = ((Gtk.Table.TableChild)(this.table1[this.legendImageError]));
        w14.LeftAttach = ((uint)(4));
        w14.RightAttach = ((uint)(5));
        w14.XOptions = ((Gtk.AttachOptions)(4));
        w14.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.legendImageExtra = new Gtk.Image();
        this.legendImageExtra.Name = "legendImageExtra";
        this.table1.Add(this.legendImageExtra);
        Gtk.Table.TableChild w15 = ((Gtk.Table.TableChild)(this.table1[this.legendImageExtra]));
        w15.TopAttach = ((uint)(2));
        w15.BottomAttach = ((uint)(3));
        w15.LeftAttach = ((uint)(4));
        w15.RightAttach = ((uint)(5));
        w15.XOptions = ((Gtk.AttachOptions)(4));
        w15.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.legendImageMissing = new Gtk.Image();
        this.legendImageMissing.Name = "legendImageMissing";
        this.table1.Add(this.legendImageMissing);
        Gtk.Table.TableChild w16 = ((Gtk.Table.TableChild)(this.table1[this.legendImageMissing]));
        w16.TopAttach = ((uint)(1));
        w16.BottomAttach = ((uint)(2));
        w16.LeftAttach = ((uint)(4));
        w16.RightAttach = ((uint)(5));
        w16.XOptions = ((Gtk.AttachOptions)(4));
        w16.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.legendImageNIEX = new Gtk.Image();
        this.legendImageNIEX.Name = "legendImageNIEX";
        this.table1.Add(this.legendImageNIEX);
        Gtk.Table.TableChild w17 = ((Gtk.Table.TableChild)(this.table1[this.legendImageNIEX]));
        w17.TopAttach = ((uint)(1));
        w17.BottomAttach = ((uint)(2));
        w17.LeftAttach = ((uint)(1));
        w17.RightAttach = ((uint)(2));
        w17.XOptions = ((Gtk.AttachOptions)(4));
        w17.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.legendImageOK = new Gtk.Image();
        this.legendImageOK.Name = "legendImageOK";
        this.table1.Add(this.legendImageOK);
        Gtk.Table.TableChild w18 = ((Gtk.Table.TableChild)(this.table1[this.legendImageOK]));
        w18.LeftAttach = ((uint)(1));
        w18.RightAttach = ((uint)(2));
        w18.XOptions = ((Gtk.AttachOptions)(4));
        w18.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.legendImageTODO = new Gtk.Image();
        this.legendImageTODO.Name = "legendImageTODO";
        this.table1.Add(this.legendImageTODO);
        Gtk.Table.TableChild w19 = ((Gtk.Table.TableChild)(this.table1[this.legendImageTODO]));
        w19.TopAttach = ((uint)(2));
        w19.BottomAttach = ((uint)(3));
        w19.LeftAttach = ((uint)(1));
        w19.RightAttach = ((uint)(2));
        w19.XOptions = ((Gtk.AttachOptions)(4));
        w19.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.vseparator1 = new Gtk.VSeparator();
        this.vseparator1.Name = "vseparator1";
        this.table1.Add(this.vseparator1);
        Gtk.Table.TableChild w20 = ((Gtk.Table.TableChild)(this.table1[this.vseparator1]));
        w20.LeftAttach = ((uint)(2));
        w20.RightAttach = ((uint)(3));
        w20.XOptions = ((Gtk.AttachOptions)(4));
        w20.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.vseparator2 = new Gtk.VSeparator();
        this.vseparator2.Name = "vseparator2";
        this.table1.Add(this.vseparator2);
        Gtk.Table.TableChild w21 = ((Gtk.Table.TableChild)(this.table1[this.vseparator2]));
        w21.TopAttach = ((uint)(1));
        w21.BottomAttach = ((uint)(2));
        w21.LeftAttach = ((uint)(2));
        w21.RightAttach = ((uint)(3));
        w21.XOptions = ((Gtk.AttachOptions)(4));
        w21.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.vseparator3 = new Gtk.VSeparator();
        this.vseparator3.Name = "vseparator3";
        this.table1.Add(this.vseparator3);
        Gtk.Table.TableChild w22 = ((Gtk.Table.TableChild)(this.table1[this.vseparator3]));
        w22.TopAttach = ((uint)(2));
        w22.BottomAttach = ((uint)(3));
        w22.LeftAttach = ((uint)(2));
        w22.RightAttach = ((uint)(3));
        w22.XOptions = ((Gtk.AttachOptions)(4));
        w22.YOptions = ((Gtk.AttachOptions)(4));
        this.expander1.Add(this.table1);
        this.GtkLabel4 = new Gtk.Label();
        this.GtkLabel4.Name = "GtkLabel4";
        this.GtkLabel4.LabelProp = Mono.Unix.Catalog.GetString("Legend");
        this.GtkLabel4.UseUnderline = true;
        this.expander1.LabelWidget = this.GtkLabel4;
        this.vbox1.Add(this.expander1);
        Gtk.Box.BoxChild w24 = ((Gtk.Box.BoxChild)(this.vbox1[this.expander1]));
        w24.Position = 3;
        w24.Expand = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.statusbar1 = new Gtk.Statusbar();
        this.statusbar1.Name = "statusbar1";
        this.statusbar1.Spacing = 6;
        // Container child statusbar1.Gtk.Box+BoxChild
        this.progressbar1 = new Gtk.ProgressBar();
        this.progressbar1.Name = "progressbar1";
        this.statusbar1.Add(this.progressbar1);
        Gtk.Box.BoxChild w25 = ((Gtk.Box.BoxChild)(this.statusbar1[this.progressbar1]));
        w25.Position = 2;
        this.vbox1.Add(this.statusbar1);
        Gtk.Box.BoxChild w26 = ((Gtk.Box.BoxChild)(this.vbox1[this.statusbar1]));
        w26.Position = 4;
        w26.Expand = false;
        w26.Fill = false;
        this.Add(this.vbox1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 648;
        this.DefaultHeight = 577;
        this.summary.Hide();
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.quit.Activated += new System.EventHandler(this.OnQuitActivated);
        this.Custom.Activated += new System.EventHandler(this.OnCustomActivated);
        this.ShowMissing.Toggled += new System.EventHandler(this.OnShowMissingToggled);
        this.ShowExtra.Toggled += new System.EventHandler(this.OnShowExtraToggled);
        this.ShowPresent.Toggled += new System.EventHandler(this.OnShowPresentToggled);
        this.ShowErrors.Toggled += new System.EventHandler(this.OnShowErrorsToggled);
        this.Refresh.Activated += new System.EventHandler(this.OnRefreshActivated);
        this.ShowTodo.Toggled += new System.EventHandler(this.OnShowTodoToggled);
        this.ShowNotImplemented.Toggled += new System.EventHandler(this.OnShowNotImplementedToggled);
        this.ToggleRowExpansionAction.Activated += new System.EventHandler(this.OnToggleRowExpansion);
    }
}
