.TH "mprof-decoder" 1
.SH NAME
mprof-decoder \- Console decoder for the logging profiler output files
.SH SYNOPSIS
.B mprof-decoder
file
.SH DESCRIPTION
.B mprof-decoder
Console decoder for the logging profiler output files
.PP
Decodes the contents of a logging profiler output file and prints the
data on standard output.
.SH Options
.PP
None
.SH ENVIRONMENT VARIABLES
.PP
None
.SH SEE ALSO
mono(1)
.BR
.SH COPYRIGHT
Copyright (C) 2008 Novell, Inc (http://www.novell.com)
