// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.UIManager UIManager;
    
    private Gtk.Action FileAction;
    
    private Gtk.Action AddCounterAction;
    
    private Gtk.Action QuitAction;
    
    private Gtk.Action HelpAction;
    
    private Gtk.Action HelpAction1;
    
    private Gtk.Action quitAction;
    
    private Gtk.Action addAction;
    
    private Gtk.Table table1;
    
    private Gtk.VBox graph_vbox;
    
    private Gtk.MenuBar menubar1;
    
    private Gtk.Toolbar toolbar1;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.UIManager = new Gtk.UIManager();
        Gtk.ActionGroup w1 = new Gtk.ActionGroup("Default");
        this.FileAction = new Gtk.Action("FileAction", Mono.Unix.Catalog.GetString("File"), null, null);
        this.FileAction.ShortLabel = Mono.Unix.Catalog.GetString("File");
        w1.Add(this.FileAction, null);
        this.AddCounterAction = new Gtk.Action("AddCounterAction", Mono.Unix.Catalog.GetString("_Add counter"), null, "gtk-add");
        this.AddCounterAction.ShortLabel = Mono.Unix.Catalog.GetString("_Add performance counter");
        w1.Add(this.AddCounterAction, null);
        this.QuitAction = new Gtk.Action("QuitAction", Mono.Unix.Catalog.GetString("_Quit"), null, "gtk-quit");
        this.QuitAction.ShortLabel = Mono.Unix.Catalog.GetString("_Quit");
        w1.Add(this.QuitAction, null);
        this.HelpAction = new Gtk.Action("HelpAction", Mono.Unix.Catalog.GetString("Help"), null, null);
        this.HelpAction.ShortLabel = Mono.Unix.Catalog.GetString("Help");
        w1.Add(this.HelpAction, null);
        this.HelpAction1 = new Gtk.Action("HelpAction1", Mono.Unix.Catalog.GetString("_Help"), null, "gtk-help");
        this.HelpAction1.ShortLabel = Mono.Unix.Catalog.GetString("_Help");
        w1.Add(this.HelpAction1, null);
        this.quitAction = new Gtk.Action("quitAction", null, null, "gtk-quit");
        w1.Add(this.quitAction, null);
        this.addAction = new Gtk.Action("addAction", null, null, "gtk-add");
        w1.Add(this.addAction, null);
        this.UIManager.InsertActionGroup(w1, 0);
        this.AddAccelGroup(this.UIManager.AccelGroup);
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("Mono Perf Monitor");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.table1 = new Gtk.Table(((uint)(3)), ((uint)(3)), false);
        this.table1.Name = "table1";
        this.table1.RowSpacing = ((uint)(6));
        this.table1.ColumnSpacing = ((uint)(6));
        // Container child table1.Gtk.Table+TableChild
        this.graph_vbox = new Gtk.VBox();
        this.graph_vbox.Name = "graph_vbox";
        this.graph_vbox.Spacing = 6;
        this.table1.Add(this.graph_vbox);
        Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table1[this.graph_vbox]));
        w2.TopAttach = ((uint)(2));
        w2.BottomAttach = ((uint)(3));
        w2.RightAttach = ((uint)(3));
        w2.XOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.UIManager.AddUiFromString("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='AddCounterAction' action='AddCounterAction'/><menuitem name='QuitAction' action='QuitAction'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='HelpAction1' action='HelpAction1'/></menu></menubar></ui>");
        this.menubar1 = ((Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
        this.menubar1.Name = "menubar1";
        this.table1.Add(this.menubar1);
        Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table1[this.menubar1]));
        w3.RightAttach = ((uint)(3));
        w3.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.UIManager.AddUiFromString("<ui><toolbar name='toolbar1'><toolitem name='quitAction' action='quitAction'/><toolitem name='AddCounterAction' action='AddCounterAction'/></toolbar></ui>");
        this.toolbar1 = ((Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar1")));
        this.toolbar1.Name = "toolbar1";
        this.toolbar1.ShowArrow = false;
        this.toolbar1.ToolbarStyle = ((Gtk.ToolbarStyle)(0));
        this.table1.Add(this.toolbar1);
        Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table1[this.toolbar1]));
        w4.TopAttach = ((uint)(1));
        w4.BottomAttach = ((uint)(2));
        w4.RightAttach = ((uint)(3));
        w4.YOptions = ((Gtk.AttachOptions)(4));
        this.Add(this.table1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 533;
        this.DefaultHeight = 436;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.AddCounterAction.Activated += new System.EventHandler(this.AddCounter);
        this.QuitAction.Activated += new System.EventHandler(this.OnQuit);
    }
}
