// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace mperfmon {
    
    
    public partial class NewCounter {
        
        private Gtk.Table table2;
        
        private Gtk.Frame frame1;
        
        private Gtk.Alignment GtkAlignment3;
        
        private Gtk.ScrolledWindow GtkScrolledWindow;
        
        private Gtk.TreeView counters;
        
        private Gtk.Label GtkLabel3;
        
        private Gtk.Frame frame2;
        
        private Gtk.Alignment GtkAlignment2;
        
        private Gtk.ScrolledWindow GtkScrolledWindow1;
        
        private Gtk.TreeView instances;
        
        private Gtk.Label GtkLabel2;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Label label1;
        
        private Gtk.ComboBox categories;
        
        private Gtk.Button buttonCancel;
        
        private Gtk.Button buttonOk;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget mperfmon.NewCounter
            this.Name = "mperfmon.NewCounter";
            this.Title = Mono.Unix.Catalog.GetString("Add performance counter");
            this.TypeHint = ((Gdk.WindowTypeHint)(1));
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.HasSeparator = false;
            // Internal child mperfmon.NewCounter.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.table2 = new Gtk.Table(((uint)(2)), ((uint)(2)), false);
            this.table2.Name = "table2";
            this.table2.RowSpacing = ((uint)(6));
            this.table2.ColumnSpacing = ((uint)(6));
            // Container child table2.Gtk.Table+TableChild
            this.frame1 = new Gtk.Frame();
            this.frame1.Name = "frame1";
            this.frame1.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frame1.Gtk.Container+ContainerChild
            this.GtkAlignment3 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment3.Name = "GtkAlignment3";
            this.GtkAlignment3.LeftPadding = ((uint)(12));
            // Container child GtkAlignment3.Gtk.Container+ContainerChild
            this.GtkScrolledWindow = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            this.counters = new Gtk.TreeView();
            this.counters.CanFocus = true;
            this.counters.Name = "counters";
            this.counters.HeadersClickable = true;
            this.GtkScrolledWindow.Add(this.counters);
            this.GtkAlignment3.Add(this.GtkScrolledWindow);
            this.frame1.Add(this.GtkAlignment3);
            this.GtkLabel3 = new Gtk.Label();
            this.GtkLabel3.Name = "GtkLabel3";
            this.GtkLabel3.LabelProp = Mono.Unix.Catalog.GetString("<b>Counters:</b>");
            this.GtkLabel3.UseMarkup = true;
            this.frame1.LabelWidget = this.GtkLabel3;
            this.table2.Add(this.frame1);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table2[this.frame1]));
            w5.TopAttach = ((uint)(1));
            w5.BottomAttach = ((uint)(2));
            // Container child table2.Gtk.Table+TableChild
            this.frame2 = new Gtk.Frame();
            this.frame2.Name = "frame2";
            this.frame2.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frame2.Gtk.Container+ContainerChild
            this.GtkAlignment2 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment2.Name = "GtkAlignment2";
            this.GtkAlignment2.LeftPadding = ((uint)(12));
            // Container child GtkAlignment2.Gtk.Container+ContainerChild
            this.GtkScrolledWindow1 = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
            this.GtkScrolledWindow1.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
            this.instances = new Gtk.TreeView();
            this.instances.CanFocus = true;
            this.instances.Name = "instances";
            this.instances.HeadersClickable = true;
            this.GtkScrolledWindow1.Add(this.instances);
            this.GtkAlignment2.Add(this.GtkScrolledWindow1);
            this.frame2.Add(this.GtkAlignment2);
            this.GtkLabel2 = new Gtk.Label();
            this.GtkLabel2.Name = "GtkLabel2";
            this.GtkLabel2.LabelProp = Mono.Unix.Catalog.GetString("<b>Instances:</b>");
            this.GtkLabel2.UseMarkup = true;
            this.frame2.LabelWidget = this.GtkLabel2;
            this.table2.Add(this.frame2);
            Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.table2[this.frame2]));
            w9.TopAttach = ((uint)(1));
            w9.BottomAttach = ((uint)(2));
            w9.LeftAttach = ((uint)(1));
            w9.RightAttach = ((uint)(2));
            // Container child table2.Gtk.Table+TableChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("Category");
            this.hbox1.Add(this.label1);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.hbox1[this.label1]));
            w10.Position = 0;
            w10.Expand = false;
            w10.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.categories = Gtk.ComboBox.NewText();
            this.categories.Name = "categories";
            this.categories.Active = 0;
            this.hbox1.Add(this.categories);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.hbox1[this.categories]));
            w11.Position = 1;
            w11.Expand = false;
            w11.Fill = false;
            this.table2.Add(this.hbox1);
            Gtk.Table.TableChild w12 = ((Gtk.Table.TableChild)(this.table2[this.hbox1]));
            w12.RightAttach = ((uint)(2));
            w12.XOptions = ((Gtk.AttachOptions)(0));
            w12.YOptions = ((Gtk.AttachOptions)(4));
            w1.Add(this.table2);
            Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(w1[this.table2]));
            w13.Position = 0;
            w13.Padding = ((uint)(6));
            // Internal child mperfmon.NewCounter.ActionArea
            Gtk.HButtonBox w14 = this.ActionArea;
            w14.Name = "dialog1_ActionArea";
            w14.Spacing = 6;
            w14.BorderWidth = ((uint)(5));
            w14.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonCancel = new Gtk.Button();
            this.buttonCancel.CanDefault = true;
            this.buttonCancel.CanFocus = true;
            this.buttonCancel.Name = "buttonCancel";
            this.buttonCancel.UseStock = true;
            this.buttonCancel.UseUnderline = true;
            this.buttonCancel.Label = "gtk-cancel";
            this.AddActionWidget(this.buttonCancel, -6);
            Gtk.ButtonBox.ButtonBoxChild w15 = ((Gtk.ButtonBox.ButtonBoxChild)(w14[this.buttonCancel]));
            w15.Expand = false;
            w15.Fill = false;
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonOk = new Gtk.Button();
            this.buttonOk.CanDefault = true;
            this.buttonOk.CanFocus = true;
            this.buttonOk.Name = "buttonOk";
            this.buttonOk.UseStock = true;
            this.buttonOk.UseUnderline = true;
            this.buttonOk.Label = "gtk-ok";
            this.AddActionWidget(this.buttonOk, -5);
            Gtk.ButtonBox.ButtonBoxChild w16 = ((Gtk.ButtonBox.ButtonBoxChild)(w14[this.buttonOk]));
            w16.Position = 1;
            w16.Expand = false;
            w16.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 565;
            this.DefaultHeight = 359;
            this.Show();
            this.categories.Changed += new System.EventHandler(this.OnCategorySelected);
            this.counters.RowActivated += new Gtk.RowActivatedHandler(this.OnCounterRow);
        }
    }
}
